spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    password: admin
    username: admin
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    database: h2